### ISSUE TITLE
The role does not allow you to specify an alternative exports file

### ISSUE THREAD

**Issue by eseyman** [robertdebock/ansible-role-nfsserver#3]
# Describe the bug

I've started using this role to deploy my nfs-server but I want to group together exports in  /etc/exports.d/*.exports
The role only allows to deploy /etc/exports (the name is hardcoded in tasks/main.yml).

## Playbook

```yaml
---
  - name: "install nfsserver"
    hosts: localhost
    connection: local
    become: yes
    roles:
      - role: robertdebock.nfsserver
        nfsserver_exports:
          - share: "/home/manu/Musique"
            owner: manu
            group: manu
            mode: "0755"
            hosts:
              - name: "192.168.1.0/24"
                options:
                  - ro
```

## Output

The role runs without errors but only deploys /etc/exports.

## Environment

- Control node OS: Fedora 40
- Control node Ansible version: 9.4.0
- Managed node OS: Fedora 40
